version: '3.2'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-app

  app:
    image: node:18-alpine
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "yarn install && yarn run dev"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: todos
    ports:
      - "3000:3000"
    networks:
      - todo-app

  readonly-app:
    image: node:18-alpine
    container_name: readonly-app
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "yarn install && node readonly-app.js"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DB: todos
    ports:
      - "3001:3000"
    networks:
      - todo-app

volumes:
  portainer_data:
  mysql_data:

networks:
  todo-app:
    driver: bridge
